// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/company" | "/[locale]/contact" | "/[locale]/solutions" | "/[locale]/solutions/[slug]" | "/[locale]/technology" | "/[locale]/technology/digital-twin" | "/[locale]/technology/fleet-management" | "/[locale]/technology/modular-wes"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = "/[locale]/solutions/brownfield" | "/[locale]/solutions/digital-twin" | "/[locale]/solutions/fleet-management" | "/[locale]/solutions/modular-wes"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/company": { "locale": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/solutions": { "locale": string; }
  "/[locale]/solutions/[slug]": { "locale": string; "slug": string; }
  "/[locale]/solutions/brownfield": { "locale": string; }
  "/[locale]/solutions/digital-twin": { "locale": string; }
  "/[locale]/solutions/fleet-management": { "locale": string; }
  "/[locale]/solutions/modular-wes": { "locale": string; }
  "/[locale]/technology": { "locale": string; }
  "/[locale]/technology/digital-twin": { "locale": string; }
  "/[locale]/technology/fleet-management": { "locale": string; }
  "/[locale]/technology/modular-wes": { "locale": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
