// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/[locale]/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/company">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solution-by-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solution-by-design">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solution-by-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/technology/digital-twin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/technology/digital-twin">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/technology/digital-twin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/technology/fleet-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/technology/fleet-management">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/technology/fleet-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/technology/modular-wes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/technology/modular-wes">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/technology/modular-wes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/technology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/technology">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/technology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/technology/specifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/technology/specifications">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/technology/specifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
